name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd ./cryogenic_plant_automation/ && cargo build --verbose && cd ..
    - name: Run tests
      run: cd ./cryogenic_plant_automation/ && cargo test --verbose && cd ..
